### ISSUE TITLE
What about `count` ?

### ISSUE THREAD

**Issue by gjuchault** [balderdashy/sails-generate-adapter#9]
Shouldn't there be a `count` method ?

**Comment by dmarcelino** [comment]
Hi @gjuchault, there is, but it's optional. If the adapter doesn't implement `.count()` waterline core will shim it using the existing `.find()`. You can implement the method to get some performance improvements, check balderdashy/sails-postgresql#171 for an example.

**Comment by gjuchault** [comment]
Thanks.
I guess it is the same for findOrCreate. I have somme trouble with the
différence with the boilerplate. Furthermore, the arguments are not clean
(collection or collectionName) etc. (I'm wrtiting an adaptater for
rethinkdb)

**Comment by dmarcelino** [comment]
`findOrCreate` is actually documented in [adapter specification](https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md#class-methods) :) BTW, if you haven't found it I suggest you read [waterline-docs - adapters](https://github.com/balderdashy/waterline-docs/blob/master/adapters/adapters.md) which I wrote after developing a waterline adapter.

BTW, are you forking one of the existing adapters: https://github.com/knownasilya/sails-rethinkdb or https://github.com/jmdobry/waterline-rethinkdb? It would be good if the community could focus on a single sails-rethinkdb adapter.
